# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip
require 'fileutils'

platform :ios, min_ios_version_supported
prepare_react_native_project!

use_frameworks! :linkage => :static
$RNFirebaseAsStaticFramework = true

target 'FocusTimer' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    installer.pods_project.targets.each do |target|
      if target.name == 'gRPC-Core'
        target.build_configurations.each do |build_config|
          build_config.build_settings['MODULEMAP_FILE'] = 'Target Support Files/gRPC-Core/gRPC-Core.modulemap'
        end
      end

      if target.name == 'gRPC-C++'
        target.build_configurations.each do |build_config|
          other_cflags = build_config.build_settings['OTHER_CFLAGS']
          next unless other_cflags

          if other_cflags.is_a?(Array)
            other_cflags = other_cflags.map do |flag|
              flag.gsub(
                '${PODS_ROOT}/Headers/Private/grpc/gRPC-Core.modulemap',
                '${PODS_ROOT}/Target Support Files/gRPC-Core/gRPC-Core.modulemap'
              )
            end
          else
            other_cflags = other_cflags.gsub(
              '${PODS_ROOT}/Headers/Private/grpc/gRPC-Core.modulemap',
              '${PODS_ROOT}/Target Support Files/gRPC-Core/gRPC-Core.modulemap'
            )
          end

          build_config.build_settings['OTHER_CFLAGS'] = other_cflags
        end
      end

      if target.name == 'React-RuntimeHermes'
        target.build_configurations.each do |build_config|
          other_cflags = build_config.build_settings['OTHER_CFLAGS']
          next unless other_cflags

          if other_cflags.is_a?(Array)
            other_cflags = other_cflags.reject { |flag| flag.include?('React-jsitooling.modulemap') }
          else
            other_cflags = other_cflags.gsub(/-fmodule-map-file=\"\$\{PODS_ROOT\}\/Headers\/Public\/react_runtime\/React-jsitooling\.modulemap\"\s*/, '')
          end

          build_config.build_settings['OTHER_CFLAGS'] = other_cflags
        end
      end

      next unless target.name == 'fmt'

      target.build_configurations.each do |build_config|
        defs = build_config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] || ['$(inherited)']
        defs = [defs] unless defs.is_a?(Array)
        defs << 'FMT_USE_CONSTEVAL=0' unless defs.include?('FMT_USE_CONSTEVAL=0')
        build_config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = defs

        cpp_flags = build_config.build_settings['OTHER_CPLUSPLUSFLAGS'] || ['$(inherited)']
        cpp_flags = [cpp_flags] unless cpp_flags.is_a?(Array)
        cpp_flags << '-DFMT_USE_CONSTEVAL=0' unless cpp_flags.include?('-DFMT_USE_CONSTEVAL=0')
        build_config.build_settings['OTHER_CPLUSPLUSFLAGS'] = cpp_flags

        build_config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
      end
    end

  end
end

post_integrate do |installer|
  grpc_xcconfigs = [
    File.join(__dir__, 'Pods', 'Target Support Files', 'gRPC-C++', 'gRPC-C++.debug.xcconfig'),
    File.join(__dir__, 'Pods', 'Target Support Files', 'gRPC-C++', 'gRPC-C++.release.xcconfig')
  ]

  grpc_xcconfigs.each do |xcconfig|
    next unless File.exist?(xcconfig)

    content = File.read(xcconfig)
    updated = content.gsub(
      '${PODS_ROOT}/Headers/Private/grpc/gRPC-Core.modulemap',
      '${PODS_ROOT}/Target Support Files/gRPC-Core/gRPC-Core.modulemap'
    )
    File.write(xcconfig, updated) if updated != content
  end

  grpc_private_dir = File.join(__dir__, 'Pods', 'Headers', 'Private', 'grpc')
  grpc_modulemap_source = File.join(__dir__, 'Pods', 'Target Support Files', 'gRPC-Core', 'gRPC-Core.modulemap')
  grpc_modulemap_dest = File.join(grpc_private_dir, 'gRPC-Core.modulemap')
  if File.exist?(grpc_modulemap_source)
    FileUtils.mkdir_p(grpc_private_dir)
    FileUtils.cp(grpc_modulemap_source, grpc_modulemap_dest)
  end

  react_jsitooling_modulemap = File.join(__dir__, 'Pods', 'Headers', 'Public', 'react_runtime', 'React-jsitooling.modulemap')
  if File.exist?(react_jsitooling_modulemap)
    content = File.read(react_jsitooling_modulemap)
    updated = content.sub(/^module\s+react_runtime\s*\{/, 'module react_jsitooling {')
    File.write(react_jsitooling_modulemap, updated) if updated != content
  end

  react_runtime_hermes_xcconfigs = [
    File.join(__dir__, 'Pods', 'Target Support Files', 'React-RuntimeHermes', 'React-RuntimeHermes.debug.xcconfig'),
    File.join(__dir__, 'Pods', 'Target Support Files', 'React-RuntimeHermes', 'React-RuntimeHermes.release.xcconfig')
  ]
  react_runtime_hermes_xcconfigs.each do |xcconfig|
    next unless File.exist?(xcconfig)

    content = File.read(xcconfig)
    updated = content.gsub(
      /-fmodule-map-file="\$\{PODS_ROOT\}\/Headers\/Public\/react_runtime\/React-jsitooling\.modulemap"\s*/,
      ''
    )
    File.write(xcconfig, updated) if updated != content
  end

  react_rctruntime_xcconfigs = [
    File.join(__dir__, 'Pods', 'Target Support Files', 'React-RCTRuntime', 'React-RCTRuntime.debug.xcconfig'),
    File.join(__dir__, 'Pods', 'Target Support Files', 'React-RCTRuntime', 'React-RCTRuntime.release.xcconfig')
  ]
  react_rctruntime_xcconfigs.each do |xcconfig|
    next unless File.exist?(xcconfig)

    content = File.read(xcconfig)
    updated = content.gsub(
      /-fmodule-map-file="\$\{PODS_ROOT\}\/Headers\/Public\/react_runtime\/React-jsitooling\.modulemap"\s*/,
      ''
    ).gsub(
      /-fmodule-map-file="\$\{PODS_ROOT\}\/Headers\/Public\/ReactCommon\/React-RuntimeApple\.modulemap"\s*/,
      ''
    )
    File.write(xcconfig, updated) if updated != content
  end

  react_runtime_apple_xcconfigs = [
    File.join(__dir__, 'Pods', 'Target Support Files', 'React-RuntimeApple', 'React-RuntimeApple.debug.xcconfig'),
    File.join(__dir__, 'Pods', 'Target Support Files', 'React-RuntimeApple', 'React-RuntimeApple.release.xcconfig')
  ]
  react_runtime_apple_xcconfigs.each do |xcconfig|
    next unless File.exist?(xcconfig)

    content = File.read(xcconfig)
    updated = content.gsub(
      /-fmodule-map-file="\$\{PODS_ROOT\}\/Headers\/Public\/react_runtime\/React-jsitooling\.modulemap"\s*/,
      ''
    )
    File.write(xcconfig, updated) if updated != content
  end

  react_target_support_dir = File.join(__dir__, 'Pods', 'Target Support Files')
  Dir.glob(File.join(react_target_support_dir, 'React*', '*.xcconfig')).each do |xcconfig|
    next unless File.file?(xcconfig)

    content = File.read(xcconfig)
    updated = content.gsub(
      /-fmodule-map-file="\$\{PODS_ROOT\}\/Headers\/Public\/react_runtime\/React-jsitooling\.modulemap"\s*/,
      ''
    ).gsub(
      /-fmodule-map-file="\$\{PODS_ROOT\}\/Headers\/Public\/ReactCommon\/React-RuntimeApple\.modulemap"\s*/,
      ''
    )
    File.write(xcconfig, updated) if updated != content
  end

  firebase_header = File.join(__dir__, 'Pods', 'Headers', 'Private', 'Firebase', 'Firebase.h')
  if File.exist?(firebase_header)
    begin
      # Firebase.h may be a symlink; resolve to the real file before chmod
      real_header = File.symlink?(firebase_header) ? File.realpath(firebase_header) : firebase_header
      FileUtils.chmod('+w', real_header)
      content = File.read(real_header)
      updated = content.gsub(
        "#import <FirebaseAuth/FirebaseAuth-Swift.h>",
        "#if __has_include(<FirebaseAuth/FirebaseAuth-Swift.h>)\n      #import <FirebaseAuth/FirebaseAuth-Swift.h>\n    #endif"
      )
      File.write(real_header, updated) if updated != content
    rescue Errno::EACCES, Errno::EPERM, StandardError
      # Skip patching if the header is not writable in this environment.
    end
  end
end
